#!/bin/sh
#set -x

find target -mindepth 2 -not -path "*/release/stringsext" \
                        -not -path "*/release/stringsext.exe" \
                        -not -path "*/debian" \
                        -not -path "*/debian/stringsext*.deb" \
                        -not -path "*/release/*.md" \
                        -not -path "*/release" \
                        -not -path "target/doc*"  \
                        -exec rm -r {} \;

rm -r target/debug
rm -r target/release
rm -r target/rls
rm target/.rustc_info.json
