#!/bin/sh
cd ..
mkdir --parents ./doc/build/html
mkdir  ./doc/build/html/_downloads
mkdir --parents ./doc/build/man/man1

# Man page
rst2man ./doc/source/stringsext--man.rst > ./doc/build/man/man1/stringsext.1
rst2html --stylesheet=./doc/source/docutils_basic.css ./doc/source/stringsext--man.rst ./doc/build/html/stringsext--man.html
# You can also use pandoc
#pandoc -s doc/source/stringsext--man.rst -t man -o man/man1/stringsext.1
gzip -f ./doc/build/man/man1/stringsext.1

# Readme page
rst2html --stylesheet=./doc/source/docutils_basic.css ./doc/source/index.rst ./doc/build/html/index.html

ln -sf ./doc/source/index.rst ./README.rst
cd  ./doc/build/html/_downloads
ln -sf ../../../../target/* .
ln -sf ../../../../doc/build/man/man1/stringsext.1.gz .


cargo rustdoc  -p stringsext -- --document-private-items 
