#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./md2man ./source/stringsext--manpage.md ./build/man/man1/stringsext.1
./md2docbook2pdf ./source/stringsext--manpage.md ./build/pdf/stringsext--manpage.pdf
./md2docbook2html ./source/stringsext--manpage.md ./build/html/stringsext--manpage.html

