#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./markdown2man ./source/stringsext--manpage.md ./build/man/man1/stringsext.1
./markdown2pdf ./source/stringsext--manpage.md ./build/pdf/stringsext--manpage.pdf
./markdown2html ./source/stringsext--manpage.md ./build/html/stringsext--manpage.html

cd ./build/html/ 
ln -s stringsext--manpage.html stringsext--man.html
