#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Man page
pandoc -f markdown -t html  --include-in-header=./source/docutils_basic.css\
       ./source/stringsext--man.md -o ./build/html/stringsext--man.html
pandoc -s ./source/stringsext--man.md -t man \
       -o ./build/man/man1/stringsext.1
gzip -f ./build/man/man1/stringsext.1

# Readme page
pandoc -f markdown -t html --include-in-header=./source/docutils_basic.css\
        ./source/README.md -o ./build/html/index.html

cd  ./build/html/_downloads
ln -sf ../../../../target/* .
ln -sf ../../../build/man/man1/stringsext.1.gz .


