#!/bin/sh
set -x
# Change to this script directory
cd $(dirname "$0")

### You might want to (re-)build the Docker image before:
#../build-env/rebuild-dev-image


../build-env/run-script          ./10-clear-targets
../build-env/run-script          ./11-test
../build-env/run-script          ./12-make-targets
../build-env/run-script          ./13-make-win-cross-compile
                                 ./14-make-doc
../build-env/run-script          ./15-build-packages
../build-env/run-script          ./16-clean-targets-keep-binaries
../build-env/run-script          ./17-make-dist
