#!/bin/sh
# Change to this script directory
cd $(dirname "$0")

### Better do these manually, to make sure that all dependencies work with 
### the current `rustc` version.
# cargo update
# cargo upgrade

rm -r ../target
rm -r ../doc/build

